name: Publish core library as Nuget package

on:
  pull_request:
    types: [closed]
    branches:
      - master
    paths:
      - BGPViewerCore/**

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.505
    - name: Restore dependencies
      working-directory: ./BGPViewerCore
      run: dotnet restore
    - name: Build
      working-directory: ./BGPViewerCore
      run: dotnet build --configuration Release --no-restore
    - name: Publish to NuGet
      working-directory: ./BGPViewerCore/bin/Release
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        VERSION: ${{ 1.0.0-alpha05 }}
        SOURCE: ${{ https://api.nuget.org/v3/index.json }}
      run: dotnet nuget push BGPViewerCore.$VERSION.nupkg --api-key $NUGET_API_KEY --source $SOURCE